project/library/models.py
from app import db
from flask_login import UserMixin

## Code Main Repository

class CodeRepo(db.Model):
    __searchable__ = ['name', 'type_of_algorithm','complexity','method','author']
    __tablename__ = 'CodeRepo'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(300))
    type_of_algorithm = db.Column(db.String(300))
    complexity = db.Column(db.String(300))
    method = db.Column(db.String(300))
    author = db.Column(db.String(300))
    file = db.Column(db.LargeBinary)
    downloads = db.Column(db.Integer)

## Algorithm types

class Types(db.Model):
    __tablename__ = 'Types'
    id = db.Column(db.Integer, primary_key=True)
    type_of_algorithm = db.Column(db.String(300))
    
## Algorithm complexity    

class Complexities(db.Model):
    __tablename__ = 'Complexity'
    id = db.Column(db.Integer, primary_key=True)
    complexity = db.Column(db.String(300))
    
## Methods of learning

class Methods(db.Model):    
    __tablename__ = 'Methods'
    id = db.Column(db.Integer, primary_key=True)
    method = db.Column(db.String(300))

project/library/views.py
from flask import Flask, render_template, redirect, request, url_for, send_file, session, request, flash, Blueprint
from flask_login import LoginManager,login_user, login_required, logout_user, current_user, UserMixin, AnonymousUserMixin
from io import BytesIO

## Blueprint Init

library_blueprint = Blueprint(
    'library', __name__,
    template_folder="templates"
    )
    
from .models import *

## Define file upload allowed extensions

ALLOWED_EXTENSIONS = set(['py'])         
    
########################################################################## MAIN DASHBOARD ###################################################################################################################    


## MAIN DASHBOARD - "LIBRARY" #######################################################
      
@library_blueprint.route('/')
@library_blueprint.route('/library')
def library():
 
    codes = CodeRepo.query.all()
    types = Types.query.all()
 
    return render_template("library.html", codes = codes, types = types, 
                            user = current_user.username)

## DOWNLOAD TEMPLATE ################################################################    
    
@library_blueprint.route('/download_code/<code_id>', methods=['GET'])
def download_code(code_id):
    the_code = CodeRepo.query.filter_by(id = code_id).first()
    click = the_code.downloads + 1                                              ## downloads counter
    the_code.downloads = click
    db.session.commit()
    
    return send_file(BytesIO(the_code.file), 
                     attachment_filename='{}.py'.format(the_code.name),         ## return file
                     as_attachment=True)
  
## INITIATE TEMPLATE UPLOAD ######################################################### 
    
@library_blueprint.route('/add_request')
def add_request():
    types = Types.query.all()
    complexities = Complexities.query.all()
    methods = Methods.query.all()
    
    
    return render_template ('add_request.html', types = types, complexities = complexities, 
                            methods = methods, user = current_user.username)
    
## DEFINE ALLOWED TEMPLATE FILE FORMAT ##############################################   
    
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS    
    
    
## UPLOAD NEW TEMPLATE HANDLING #####################################################   
    
@library_blueprint.route('/new_code', methods = ['POST'])
def new_code():
    codes = CodeRepo.query.all()
    
    ## Exceptions handling:
    
    if not 'inputFile' in request.files:
        return render_template ('error.html', user = current_user.username)
        
    if not 'type_of_algorithm' in request.form or not 'complexity' in request.form:
        return render_template ('error.html', user = current_user.username)    
    if not 'method' in request.form:
        return render_template ('error.html', user = current_user.username)
    if request.form['name'] == '' or request.form['author'] == '':
        return render_template ('error.html', user = current_user.username)
    
    ## All good
    else:    
        code_file = request.files['inputFile']                                  ## check file format    
        if code_file and allowed_file(code_file.filename):
            code_file = code_file.read()
        else:
            return render_template ('error.html', user = current_user.username) 
            
        code = CodeRepo(name=request.form['name'],
                        type_of_algorithm=request.form['type_of_algorithm'],
                        complexity=request.form['complexity'],
                        method=request.form['method'],
                        author=request.form['author'],
                        file = code_file,
                        downloads = 0)
        db.session.add(code)
        db.session.commit()
        return redirect(url_for("library.library"))

## EDITING TEMPLATE INITIATION ######################################################
    
@library_blueprint.route('/edit_code/<code_id>')
def edit_code(code_id):
    the_code = CodeRepo.query.filter_by(id = code_id).first()
    types = Types.query.all()
    complexities = Complexities.query.all()
    methods = Methods.query.all()
    return render_template('edit_code.html', code = the_code, types = types, 
                            complexities = complexities, methods = methods, 
                            user = current_user.username)    
    
    
## UPDATE TEMPLATE HANDLING #########################################################

@library_blueprint.route('/update_code/<code_id>', methods=["POST"])
def update_code(code_id):
    the_code = CodeRepo.query.filter_by(id = code_id).first()

    the_code.name=request.form['name']
    the_code.type_of_algorithm=request.form['type_of_algorithm']
    the_code.complexity=request.form['complexity']
    the_code.method=request.form['method']
    the_code.author=request.form['author']
    
    ## Exceptions
    
    if request.form['name'] == '' or request.form['author'] == '':
        return render_template ('error.html', user = current_user.username)
    if 'inputFile' in request.files:
        code_file = request.files['inputFile']
        if code_file and allowed_file(code_file.filename):
            code_file = code_file.read()
            the_code.file = code_file
            db.session.commit()
            return redirect(url_for("library.library"))
        else:
            return render_template ('error.html', user = current_user.username)
            
    ## All good
    
    else:    
        db.session.commit()
        return redirect(url_for("library.library"))
    
## DELETE TEMPLATE HANDLING #########################################################    
    
@library_blueprint.route('/delete_code/<code_id>')
def delete_code(code_id):
    the_code = CodeRepo.query.filter_by(id = code_id).first()
    db.session.delete(the_code)
    db.session.commit()
    return redirect(url_for("library.library"))    

project/library/templates/error.html
{% extends 'base.html' %} {% block content %}

<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>

<div class="row">
    <div class="col-md-2 text-center"></div>
    <div class="col-md-8 text-center">

        <div class="card" id="title_card">
            <div class="row">
                <h2>Please fill out all required fields and make sure that uploaded file is *.py</h2>
            </div>
            <div class="row">
                <a href="{{url_for('library.library')}}"  onclick="goBack()" class="waves-effect waves-light btn-large" id="add"><i class="large material-icons left">keyboard_return</i>Back to Template</a>
            </div>
        </div>
    </div>
    <div class="col-md-2 text-center"></div>
</div>

{% endblock %}

project/library/templates/library.1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ML Dashboard</title>
    <!-- Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Materialize-->
    <link rel="stylesheet" href="{{url_for('static', filename='materialize/css/materialize.min.css')}}" media="screen,projection" />
    <!-- Bootstrap-->
    <link href="{{url_for('static', filename='css/bootstrap.css')}}" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="{{url_for('static', filename='css/font-awesome.css')}}" rel="stylesheet" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <!-- Custom Styles-->
    <link href="{{url_for('static', filename='css/custom-styles.css')}}" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="{{url_for('static', filename='js/morris/morris-0.4.3.min.css')}}" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <!-- jQuery & GitHub -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{url_for('static', filename='js/github-information.js')}}"></script>
</head>


<body>
    <!-- WRAPPER -->
    <div id="wrapper">


        <!-- TOP NAVBAR -->
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand waves-effect waves-dark" href="{{url_for('library.library')}}"><i class="large material-icons">blur_on</i><strong>ML Dashboard</strong></a>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li><a class="dropdown-button waves-effect waves-dark" data-activates="dropdown1"><i class="fa fa-user fa-fw" id="top_icon"></i> <b>{{user}}</b></a></li>
            </ul>
        </nav>
        
        <!-- DROPDOWN -->
        <ul id="dropdown1" class="dropdown-content">
            <li><a href="{{ url_for('users.login') }}"><i class="fa fa-user fa-fw" style="color:#FFCB9A;"></i><b>Log In</b></a>
            </li>
            <li><a href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt" style="color:#FFCB9A;"></i><b>Log Out<b></a>
            </li>
            <li><a href="{{ url_for('users.signup') }}"><i class="fas fa-tasks" style="color:#FFCB9A; margin-right:2px"></i><b>Sign In<b></a>
            </li>
        </ul>    

        <!--/. TOP NAVBAR ****************************************************************************************************************************************************************************************** -->

        <!-- PAGE-WRAPPER -->
        <div id="page-wrapper">
            <!-- PAGE-INDEX -->
            <div id="page-index">
                <div class="row"></div>
                <div class="col-md-12 col-lg-9 text-center">
                    <div class="card" id="title_card">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-3 text-left">
                                <div class="row">
                                <h3>Available Code Templates:</h3>
                            </div>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-5 text-center">
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-4 text-left">
                                <div class="row">
                                    <div class="col-md-2 text-left">
                                        <h3>Contribute:</h3>
                                    </div>
                                    <div class="col-md-0 col-lg-2 text-center">
                                    </div>
                                    <div class="col-md-6 col-lg-4 text-left">
                                        <a href="{{url_for('library.add_request')}}" class="waves-effect waves-light btn btn_small" id="add">ADD TEMPLATE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-left">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th class="center">Model Name</th>
                                                <th class="center">Type of Estimator</th>
                                                <th class="center">Complexity</th>
                                                <th class="center">Learning Method</th>
                                                <th class="center">Author</th>
                                                <th class="center">Edit</th>
                                                <th class="center">Delete</th>
                                                <th class="center">Download</th>
                                                <th class="center">Downloads</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for data in codes%}
                                            <tr class="odd gradeA">
                                                <td class="center">{{data.name}}</td>
                                                <td class="center"><a href="{{url_for('algorithms.summary', type_id = data.type_of_algorithm)}}" class="waves-effect waves-light btn btn_small">{{data.type_of_algorithm}}</a></td>
                                                <td class="center">{{data.complexity}}</td>
                                                <td class="center">{{data.method}}</td>
                                                <td class="center">{{data.author}}</td>

                                                <td class="center">
                                                    <a href="{{url_for('library.edit_code', code_id=data.id)}}" class="waves-effect waves-light btn btn_small">Edit</a>
                                                </td>
                                                <td class="center">
                                                    <a href="{{url_for('library.delete_code', code_id=data.id)}}" class="waves-effect waves-light btn btn_small">Delete</a>
                                                </td>
                                                <td class="center">
                                                    <form action="{{url_for('library.download_code', code_id=data.id) }}" method="GET" enctype="multipart/form-data">
                                                        <button type="Download" class="btn btn-default">Download</button>
                                                    </form>
                                                </td>
                                                <td class="center">{{data.downloads}}</td>
                                            </tr>

                                            {% endfor%}

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3 text-center">
                    <div class="row">
                        <div class="card text-left" id="extra_card">
                            <div class="row">
                                <h3>Types of Estimator:</h3>
                            </div>
                            {% for type in types%}

                            <a href="{{url_for('algorithms.summary', type_id=type.type_of_algorithm)}}" class="waves-effect waves-light btn btn_small" id="add">{{type.type_of_algorithm}}</a>
                            <div class="row">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="card" id="extra_card">
                            <div class="row text-left">
                                <h3>Check other projects:</h3>
                            </div>
                            <div class="row text-left">
                                <input type="text" id="gh-username" value="LukaszMalucha" oninput="fetchGitHubInformation()" />
                            </div>
                            <div class="row">
                                <div id="repo_content">
                                    <div id="gh-repo-data"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- PAGE-INDEX -->
            </div>
            <!-- PAGE-WRAPPER -->
        </div>
        <!-- WRAPPER -->

        <!-- jQuery Js -->
        <script src="{{url_for('static', filename='js/jquery-1.10.2.js')}}"></script>

        <!-- Bootstrap Js -->
        <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

        <!-- Materialize Js -->
        <script src="{{url_for('static', filename='materialize/js/materialize.min.js')}}"></script>

        <!-- Metis Menu Js -->
        <script src="{{url_for('static', filename='js/jquery.metisMenu.js')}}"></script>

        <script src="{{url_for('static', filename='js/dataTables/jquery.dataTables.js')}}"></script>
        <script src="{{url_for('static', filename='js/dataTables/dataTables.bootstrap.js')}}"></script>
        <script>
            $(document).ready(function() {
                $('#dataTables-example').dataTable();
            });
        </script>

        <!-- Custom Js -->
        <script src="{{url_for('static', filename='js/custom-scripts.js')}}"></script>

        <!-- Morris Chart Js -->
        <script src="{{url_for('static', filename='js/morris/raphael-2.1.0.min.js')}}"></script>
        <script src="{{url_for('static', filename='js/morris/morris.js')}}"></script>


        <script src="{{url_for('static', filename='js/easypiechart.js')}}"></script>
        <script src="{{url_for('static', filename='js/easypiechart-data.js')}}"></script>

        <script src="{{url_for('static', filename='js/Lightweight-Chart/jquery.chart.js')}}"></script>

</body>

</html>

project/library/templates/library.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ML Dashboard</title>
    <!-- Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Materialize-->
    <link rel="stylesheet" href="{{url_for('static', filename='materialize/css/materialize.min.css')}}" media="screen,projection" />
    <!-- Bootstrap-->
    <link href="{{url_for('static', filename='css/bootstrap.css')}}" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="{{url_for('static', filename='css/font-awesome.css')}}" rel="stylesheet" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <!-- Custom Styles-->
    <link href="{{url_for('static', filename='css/custom-styles.css')}}" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="{{url_for('static', filename='js/morris/morris-0.4.3.min.css')}}" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <!-- jQuery & GitHub -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{url_for('static', filename='js/github-information.js')}}"></script>
</head>


<body>
    <!-- WRAPPER -->
    <div id="wrapper">


        <!-- TOP NAVBAR -->
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand waves-effect waves-dark" href="{{url_for('library.library')}}"><i class="large material-icons">blur_on</i><strong>ML Dashboard</strong></a>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li><a class="dropdown-button waves-effect waves-dark" data-activates="dropdown1"><i class="fa fa-user fa-fw" id="top_icon"></i> <b>{{user}}</b></a></li>
            </ul>
        </nav>
        
        <!-- DROPDOWN -->
        <ul id="dropdown1" class="dropdown-content">
            <li><a href="{{ url_for('users.login') }}"><i class="fa fa-user fa-fw" style="color:#FFCB9A;"></i><b>Log In</b></a>
            </li>
            <li><a href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt" style="color:#FFCB9A;"></i><b>Log Out<b></a>
            </li>
            <li><a href="{{ url_for('users.signup') }}"><i class="fas fa-tasks" style="color:#FFCB9A; margin-right:2px"></i><b>Sign In<b></a>
            </li>
        </ul>    

        <!--/. TOP NAVBAR ****************************************************************************************************************************************************************************************** -->

        <!-- PAGE-WRAPPER -->
        <div id="page-wrapper">
            <!-- PAGE-INDEX -->
            <div id="page-index">
                <div class="row"></div>
                <div class="col-md-12 col-lg-9 text-center">
                    <div class="card" id="title_card">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-3 text-left">
                                <div class="row">
                                <h3>Available Code Templates:</h3>
                            </div>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-5 text-center">
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-4 text-left">
                                <div class="row">
                                    <div class="col-md-2 text-left">
                                        <h3>Contribute:</h3>
                                    </div>
                                    <div class="col-md-0 col-lg-2 text-center">
                                    </div>
                                    <div class="col-md-6 col-lg-4 text-left">
                                        <a href="{{url_for('library.add_request')}}" class="waves-effect waves-light btn btn_small" id="add">ADD TEMPLATE</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-left">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th class="center">Model Name</th>
                                                <th class="center">Type of Estimator</th>
                                                <th class="center">Complexity</th>
                                                <th class="center">Learning Method</th>
                                                <th class="center">Author</th>
                                                <th class="center">Edit</th>
                                                <th class="center">Delete</th>
                                                <th class="center">Download</th>
                                                <th class="center">Downloads</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for data in codes%}
                                            <tr class="odd gradeA">
                                                <td class="center">{{data.name}}</td>
                                                <td class="center"><a href="{{url_for('algorithms.summary', type_id = data.type_of_algorithm)}}" class="waves-effect waves-light btn btn_small">{{data.type_of_algorithm}}</a></td>
                                                <td class="center">{{data.complexity}}</td>
                                                <td class="center">{{data.method}}</td>
                                                <td class="center">{{data.author}}</td>

                                                <td class="center">
                                                    <a href="{{url_for('library.edit_code', code_id=data.id)}}" class="waves-effect waves-light btn btn_small">Edit</a>
                                                </td>
                                                <td class="center">
                                                    <a href="{{url_for('library.delete_code', code_id=data.id)}}" class="waves-effect waves-light btn btn_small">Delete</a>
                                                </td>
                                                <td class="center">
                                                    <form action="{{url_for('library.download_code', code_id=data.id) }}" method="GET" enctype="multipart/form-data">
                                                        <button type="Download" class="btn btn-default">Download</button>
                                                    </form>
                                                </td>
                                                <td class="center">{{data.downloads}}</td>
                                            </tr>

                                            {% endfor%}

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3 text-center">
                    <div class="row">
                        <div class="card text-left" id="extra_card">
                            <div class="row">
                                <h3>Types of Estimator:</h3>
                            </div>
                            {% for type in types%}

                            <a href="{{url_for('algorithms.summary', type_id=type.type_of_algorithm)}}" class="waves-effect waves-light btn btn_small" id="add">{{type.type_of_algorithm}}</a>
                            <div class="row">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="card" id="extra_card">
                            <div class="row text-left">
                                <h3>Check other projects:</h3>
                            </div>
                            <div class="row text-left">
                                <input type="text" id="gh-username" value="LukaszMalucha" oninput="fetchGitHubInformation()" />
                            </div>
                            <div class="row">
                                <div id="repo_content">
                                    <div id="gh-repo-data"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- PAGE-INDEX -->
            </div>
            <!-- PAGE-WRAPPER -->
        </div>
        <!-- WRAPPER -->

        <!-- jQuery Js -->
        <script src="{{url_for('static', filename='js/jquery-1.10.2.js')}}"></script>

        <!-- Bootstrap Js -->
        <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

        <!-- Materialize Js -->
        <script src="{{url_for('static', filename='materialize/js/materialize.min.js')}}"></script>

        <!-- Metis Menu Js -->
        <script src="{{url_for('static', filename='js/jquery.metisMenu.js')}}"></script>

        <script src="{{url_for('static', filename='js/dataTables/jquery.dataTables.js')}}"></script>
        <script src="{{url_for('static', filename='js/dataTables/dataTables.bootstrap.js')}}"></script>
        <script>
            $(document).ready(function() {
                $('#dataTables-example').dataTable();
            });
        </script>

        <!-- Custom Js -->
        <script src="{{url_for('static', filename='js/custom-scripts.js')}}"></script>

        <!-- Morris Chart Js -->
        <script src="{{url_for('static', filename='js/morris/raphael-2.1.0.min.js')}}"></script>
        <script src="{{url_for('static', filename='js/morris/morris.js')}}"></script>


        <script src="{{url_for('static', filename='js/easypiechart.js')}}"></script>
        <script src="{{url_for('static', filename='js/easypiechart-data.js')}}"></script>

        <script src="{{url_for('static', filename='js/Lightweight-Chart/jquery.chart.js')}}"></script>

</body>

</html>