project/users/views.py
from flask import Flask, render_template, redirect, request, url_for, send_file, session, request, flash, Blueprint
from flask_login import LoginManager,login_user, login_required, logout_user, current_user, UserMixin, AnonymousUserMixin


## Blueprint Init

users_blueprint = Blueprint(
    'users', __name__,
    template_folder="templates"
    )

from app import db
from .forms import *
from .models import User

########################################################################## USER VIEWS ###################################################################################################################  


## SIGN UP ##########################################################################

@users_blueprint.route('/signup', methods=["GET", "POST"])
def signup():
    form = RegisterForm()
    hashed_password = generate_password_hash(form.password.data, method='sha256')           ## password get hashed for security purposes
    if form.validate_on_submit(): 
        new_user = User(username=form.username.data, email=form.email.data, 
                        password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('users.login'))
 
    return render_template('signup.html', form=form)                            ## passing signup form to signup template
    
    
## LOGIN ############################################################################

@users_blueprint.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()
    message = 'Invalid username or password'  
    
    if form.validate_on_submit():                                               ## if form was submitted....
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                return redirect(url_for('library.library'))
        
        return render_template('login.html', form=form, message=message)          
    
    return render_template('login.html', form=form)                             ## passing login form to login template    


## LOGOUT ###########################################################################

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ML Dashboard</title>
    <!-- Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Materialize-->
    <link rel="stylesheet" href="{{url_for('static', filename='materialize/css/materialize.min.css')}}" media="screen,projection" />
    <!-- Bootstrap-->
    <link href="{{url_for('static', filename='css/bootstrap.css')}}" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="{{url_for('static', filename='css/font-awesome.css')}}" rel="stylesheet" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <!-- Custom Styles-->
    <link href="{{url_for('static', filename='css/custom-styles.css')}}" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="{{url_for('static', filename='js/morris/morris-0.4.3.min.css')}}" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>



<body>
    <!-- WRAPPER -->
    <div id="wrapper">


         <!-- TOP NAVBAR -->
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand waves-effect waves-dark" href="{{url_for('library.library')}}"><i class="large material-icons">blur_on</i><strong>ML Dashboard</strong></a>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li><a class="dropdown-button waves-effect waves-dark" data-activates="dropdown1"><i class="fa fa-user fa-fw" id="top_icon"></i> <b>{{user}}</b></a></li>
            </ul>
        </nav>
        
        <!-- DROPDOWN -->
        <ul id="dropdown1" class="dropdown-content">
            <li><a href="{{ url_for('users.login') }}"><i class="fa fa-user fa-fw" style="color:#FFCB9A;"></i><b>Log In</b></a>
            </li>
            <li><a href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt" style="color:#FFCB9A;"></i><b>Log Out<b></a>
            </li>
            <li><a href="{{ url_for('users.signup') }}"><i class="fas fa-tasks" style="color:#FFCB9A; margin-right:2px"></i><b>Sign In<b></a>
            </li>
        </ul> 


        <!--/. TOP NAVBAR ****************************************************************************************************************************************************************************************** -->

        <!-- PAGE-WRAPPER -->
        <div id="page-wrapper">
            <!-- PAGE-INDEX -->
            <div id="page-index">
                <div class="dashboard-cards">
                    {% block content %} {% endblock %}





                </div>

            </div>
            <!-- PAGE-INDEX -->

        </div>
        
        <!-- PAGE-WRAPPER -->

    </div>
    <!-- WRAPPER -->

    <!-- jQuery Js -->
    <script src="{{url_for('static', filename='js/jquery-1.10.2.js')}}"></script>

    <!-- Bootstrap Js -->
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

    <!-- Materialize Js -->
    <script src="{{url_for('static', filename='materialize/js/materialize.min.js')}}"></script>

    <!-- Metis Menu Js -->
    <script src="{{url_for('static', filename='js/jquery.metisMenu.js')}}"></script>
    
    <script src="{{url_for('static', filename='js/dataTables/jquery.dataTables.js')}}"></script>
    <script src="{{url_for('static', filename='js/dataTables/dataTables.bootstrap.js')}}"></script>
    <script>
        $(document).ready(function() {
            $('#dataTables-example').dataTable();
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.collapsible').collapsible();
            $('select').material_select();
            $(".button-collapse").sideNav();
        });
    </script>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <!-- Custom Js -->
    <script src="{{url_for('static', filename='js/custom-scripts.js')}}"></script>

    <!-- Morris Chart Js -->
    <script src="{{url_for('static', filename='js/morris/raphael-2.1.0.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/morris/morris.js')}}"></script>


    <script src="{{url_for('static', filename='js/easypiechart.js')}}"></script>
    <script src="{{url_for('static', filename='js/easypiechart-data.js')}}"></script>

    <script src="{{url_for('static', filename='js/Lightweight-Chart/jquery.chart.js')}}"></script>

</body>

</html>

templates/classificationorg.html
{% extends 'base.html' %} {% block content %}
<div class="row" id="menu_row">
    <div class="col-md-12 text-center">
        <div class="card" id="info_content">
            <h2>Dataset</h2>
        </div>
    </div>
</div>
<div class="row" id="menu_row">
    <div class="col-md-4 text-center">
        <div class="card" id="info_content">
            <h2>Preprocessing</h2>
            <div class="card-panel">
                <p>No. of Rows: {{rows}}</p>
                <p>No. of Columns: {{columns}}</p>
                <p>Statistical</p>
                {{describe | safe}}

            </div>
        </div>
    </div>
    <div class="col-md-8 text-center">
        <div class="card" id="info_content">
            <h2>Dataset</h2>
            <div class="card-panel">
                {{data | safe}}
            </div>
        </div>
    </div>
</div>
<div class="row" id="menu_row">
    <div class="col-md-12 text-center">
        <div class="card" id="info_content">
            <h2>Dataset</h2>
        </div>
    </div>
</div>
<div class="row" id="menu_row">
    <div class="col-md-12 text-center">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 text-center">
            <div class="row">
                <div class="card" id="info_content">
                        <select id="classifier" name="classifier">
                          <h2><option value="" disabled selected>Choose Classifier</option></h2>
                          {% for classifier in classifiers %}
                          <option value={{classifier.name}}>{{classifier.name}}</option>
                          {% endfor %}
                        </select>
                        <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </div>
        <div class="col-md-8 text-center">
            <div class="row">
                <div class="card" id="info_content">
                    <h2>Plot</h2>
                    {{pred}}
                </div>
            </div>
            <div class="row">
                <div class="card" id="info_content">
                    <div class="card-panel">
                        {{pred}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}